@startuml ビジネスマッチング
[*] --> 依頼一覧: 依頼一覧メニュー

依頼一覧 --> 依頼編集: 依頼リスト
依頼編集 --> 依頼一覧: 変更／削除／戻るボタン

依頼一覧 --> 依頼作成: 新規作成ボタン
依頼作成 --> 依頼一覧: 作成／戻るボタン

依頼一覧 --> 依頼一覧: F/R/P
依頼編集 --> 案件一覧: 応募

依頼一覧: bizmatch_requests
依頼作成: bizmatch_requests/new
依頼編集: bizmatch_requests/edit

[*] --> 案件一覧: 応募一覧メニュー

案件一覧 --> 案件編集: 応募リスト
案件編集 --> 案件一覧: 戻るボタン

案件一覧 --> 案件一覧: F/R/P
案件編集 --> 案件編集: 変更／発注／受注／辞退

案件一覧: bizmatch_deals
案件編集: bizmatch_deals/edit
@enduml
