@startuml ナビゲーション
hide empty description
[*] --> ホーム
[*] --> 業務日報
業務日報: ・業務日報一覧\n・業務日報明細一覧
[*] --> 業務処理簿
[*] --> 進捗管理
進捗管理: ・目標一覧\n・全体進捗状況
[*] --> ビジネスマッチング
ビジネスマッチング: ・依頼一覧\n・案件一覧
[*] --> 設定
設定: ・グループ一覧\n・ユーザー一覧\n・関与先一覧\n・システム管理
[*] --> サインアウト
@enduml
