@startuml 設定
[*] --> グループ一覧: グループ一覧メニュー

グループ一覧 --> グループ編集: グループリスト
グループ編集 --> グループ一覧: 変更／削除／戻るボタン

グループ一覧 --> グループ作成: 新規作成ボタン
グループ作成 --> グループ一覧: 作成／戻るボタン

グループ一覧 --> グループ一覧: F/R/P

グループ一覧: master_groups
グループ作成: master_groups/new
グループ編集: master_groups/edit

[*] --> ユーザー一覧: ユーザー一覧メニュー

ユーザー一覧 --> ユーザー編集: ユーザーリスト
ユーザー編集 --> ユーザー一覧: 変更／削除／戻るボタン

ユーザー一覧 --> ユーザー作成: 新規作成ボタン
ユーザー作成 --> ユーザー一覧: 作成／戻るボタン

ユーザー一覧 --> ユーザー一覧: F/R/P

ユーザー一覧: master_users
ユーザー作成: master_users/new
ユーザー編集: master_users/edit

[*] --> 関与先一覧: 関与先一覧メニュー

関与先一覧 --> 関与先編集: 関与先リスト
関与先編集 --> 関与先一覧: 変更／削除／戻るボタン

関与先一覧 --> 関与先作成: 新規作成ボタン
関与先作成 --> 関与先一覧: 作成／戻るボタン

関与先一覧 --> 関与先一覧: F/R/P

関与先一覧: master_companies
関与先作成: master_companies/new
関与先編集: master_companies/edit

[*] -> システム管理: システム管理メニュー

システム管理: admin
@enduml
